In [1]:
import pandas as pd
import os

In [2]:
os.getcwd()

'C:\\Users\\Nyachomo\\OneDrive\\Desktop\\datascience'

In [3]:
df=pd.read_excel('datasets/nyeri.xlsx')

In [5]:
df.head(4)

,student_name,student_class,student_course,student_year,student_gender,student_category,student_adm_no,attachment_period,year,attachment_start_date,attachment_end_date,company_name,sector_name,placement_status,graded,assigned_manual,student_workbehaviour_grading_score,student_skills_grading_score,student_knowledge_grading_score,student_final_score
0,Allan Thiga Maina,NNP/EIT4/25J1,ELECTRICAL INSTALLATION TECHNOLOGY,1.0,Male,CBS,54056,sept-dec,2025.0,2025-09-01,2025-12-31,SAMTECH ELECTRICALS,"Electrical & Electronics Engineering, Electric...",Placed,Not Graded,Assigned,10.0,38.6,NaN,NaN
1,Bernad Ndirangu Mwangi,NNP/EIT4/25J1,ELECTRICAL INSTALLATION TECHNOLOGY,1.0,Male,CBS,51732,sept-dec,2025.0,2025-09-01,2025-12-31,KARATINA SUBCOUNTY HOSPITAL,"HEALTH AND CARE, Health Care Giver, Healthcare...",Placed,Graded,Assigned,20.0,51.4,15.0,86.0
2,Isaac Kanja Kabuchu,NNP/EIT4/25J1,ELECTRICAL INSTALLATION TECHNOLOGY,1.0,Male,CBS,53862,sept-dec,2025.0,2025-09-01,2025-12-31,NYERI RURINGU,NaN,Placed,Not Graded,Assigned,NaN,NaN,NaN,NaN
3,Isaac Kihagi Biru,NNP/EIT4/25J1,ELECTRICAL INSTALLATION TECHNOLOGY,1.0,Male,CBS,51609,sept-dec,2025.0,2025-09-01,2025-12-31,KENYA POWER NYERI,"Electrical & Electronics Engineering, Electric...",Placed,Graded,Assigned,20.0,60.0,20.0,100.0

In [6]:
df.dtypes

student_name                            object
student_class                              str
student_course                             str
student_year                           float64
student_gender                             str
student_category                           str
student_adm_no                          object
attachment_period                          str
year                                   float64
attachment_start_date                      str
attachment_end_date                        str
company_name                               str
sector_name                                str
placement_status                           str
graded                                     str
assigned_manual                            str
student_workbehaviour_grading_score    float64
student_skills_grading_score           float64
student_knowledge_grading_score        float64
student_final_score                    float64
dtype: object

In [13]:
#CONVERTIND GRADING SCORE TO INT
df['student_workbehaviour_grading_score']=pd.to_numeric(df['student_workbehaviour_grading_score'],errors='coerce')

In [17]:
df['student_gender'].value_counts()

student_gender
Male       9932
Female     6078
F           278
MALE        229
M           184
FEMALE      129
male         92
female       32
Male          3
FEMale        1
FeMale        1
FE4MALE       1
Name: count, dtype: int64

In [18]:
df['student_gender']=df['student_gender'].str.strip().str.upper()

In [19]:
df['student_gender'].value_counts()

student_gender
MALE       10256
FEMALE      6241
F            278
M            184
FE4MALE        1
Name: count, dtype: int64

In [20]:
df['student_gender']=df['student_gender'].map({
    'MALE':'MALE',
    'FEMALE':'FEMALE',
    'F':'FEMALE',
    'M':'MALE',
    'FE4MALE':'FEMALE'
})

In [21]:
df['student_gender'].value_counts()

student_gender
MALE      10440
FEMALE     6520
Name: count, dtype: int64

In [23]:
df.groupby('student_gender').size()

student_gender
FEMALE     6520
MALE      10440
dtype: int64

In [24]:
##GROUP BY GENDER AND FIND THE MEAN OF THE FINAL SCORE
df.groupby('student_gender')['student_final_score'].mean()

student_gender
FEMALE    93.489197
MALE      92.929444
Name: student_final_score, dtype: float64

In [25]:
df.groupby('student_gender')['student_final_score'].max()

student_gender
FEMALE    135.0
MALE      126.0
Name: student_final_score, dtype: float64

In [27]:
##MINIMUM VALUE PER GROUP
df.groupby('student_gender')['student_final_score'].min()

student_gender
FEMALE    1.0
MALE      1.0
Name: student_final_score, dtype: float64

In [28]:
##FINDING SUM OF THE TOTAL FINAL SCORE OF EACH GROUP
df.groupby('student_gender')['student_final_score'].sum()

student_gender
FEMALE    289910.0
MALE      334546.0
Name: student_final_score, dtype: float64

In [29]:
##GROUP BY AND COUNTS
df.groupby('student_gender').count()

,student_name,student_class,student_course,student_year,student_category,student_adm_no,attachment_period,year,attachment_start_date,attachment_end_date,company_name,sector_name,placement_status,graded,assigned_manual,student_workbehaviour_grading_score,student_skills_grading_score,student_knowledge_grading_score,student_final_score
student_gender,,,,,,,,,,,,,,,,,,,
FEMALE,6520,6520,6519,4558,6520,6520,6447,6447,6447,6447,5469,4996,6520,6520,6520,3250,3539,3368,3101
MALE,10440,10440,10440,5524,10440,10440,8189,8189,8189,8189,6479,5898,10440,10440,10440,3867,4342,4023,3600

In [34]:
##GROUBY AND COMPUTE STATISTICAL SUMMARY
df.groupby('student_gender')['student_final_score'].agg([
    'count','min','mean','max','size','median','std','var','first','last','nunique'
])

,count,min,mean,max,size,median,std,var,first,last,nunique
student_gender,,,,,,,,,,,
FEMALE,3101,1.0,93.489197,135.0,6520,100.0,12.524800,156.870609,100.0,100.0,78
MALE,3600,1.0,92.929444,126.0,10440,100.0,13.368109,178.706329,86.0,100.0,80

In [39]:
##FINDING THE VARIANCE ALONE
df.groupby('student_gender')['student_final_score'].last()

student_gender
FEMALE    100.0
MALE      100.0
Name: student_final_score, dtype: float64

In [47]:
df.groupby(['student_gender','student_year'])['student_final_score'].max()

student_gender  student_year
FEMALE          1.0             100.0
                2.0             135.0
                3.0             100.0
                4.0             100.0
                6.0               NaN
MALE            1.0             100.0
                2.0             126.0
                3.0             100.0
                4.0             100.0
                6.0             100.0
Name: student_final_score, dtype: float64

In [53]:
df.groupby(['student_gender','year','attachment_period'])['student_skills_grading_score'].agg([
    'count','size','max','min','median','std','var','first','last','nunique','mean'
])

                                             count  size    max   min  median  \
student_gender year   attachment_period
FEMALE         2023.0 August-November           74   210   60.0   2.2    60.0
                      May Attachment             0    41    NaN   NaN     NaN
                      Sept - Nov                23  1041   60.0  18.0    60.0
               2024.0 AUG-DEC                   62   103   60.0  26.0    60.0
                      DUAL SEP - NOV             9    10   59.0  12.5    31.5
                      January -  April         147   524   60.0   1.2    60.0
                      MAY - JULY               235   342   60.0   0.0    60.0
                      Nov - Dec                  1    11    0.0   0.0     0.0
                      Sep - Dec                459   732   60.0   1.2    60.0
               2025.0 JAN-APRIL DUAL            18    26  106.8   1.4    45.3
                      Jan-April                480   581   60.0   2.3    60.0
                      May - Aug                591   830   60.0   0.0    60.0
                      PHARMACY JULY-AUG          0     6    NaN   NaN     NaN
                      SEPT-DEC dual             16    26   59.5  27.8    53.6
                      may-aug dual training     25    31   60.0  22.8    45.7
                      pharmacy april-june        0    11    NaN   NaN     NaN
                      sept-dec                 600   816   60.0   0.0    60.0
               2026.0 AUG-OCT PHARMACY           0     5    NaN   NaN     NaN
                      jan-april                416   635   60.0   0.0    60.0
                      jan-april dual            34    42   60.0   4.6    53.1
                      may-aug                  331   402   60.0   0.0    60.0
                      may-aug dual              18    22   57.3   0.0     0.0
MALE           2023.0 August-November          161   267   60.0   0.0    60.0
                      May Attachment             0    48    NaN   NaN     NaN
                      Sept - Nov                21  1191   60.0  31.3    60.0
               2024.0 AUG-DEC                   15    30   60.0  50.7    60.0
                      DUAL SEP - NOV            55    65   79.3  28.2    50.8
                      January -  April         146   493   60.0   0.0    60.0
                      MAY - JULY               200   323   60.0   0.0    60.0
                      Nov - Dec                  7    13   60.0  60.0    60.0
                      Sep - Dec                739  1059   60.0   0.0    60.0
               2025.0 JAN-APRIL DUAL            20    41  103.5  26.1    46.8
                      Jan-April                464   589   60.0   0.0    60.0
                      May - Aug                600  1048   60.0   0.0    60.0
                      PHARMACY JULY-AUG          0     4    NaN   NaN     NaN
                      SEPT-DEC dual             25    64   60.0   0.0    49.1
                      may-aug dual training     45    64   60.0   1.9    52.0
                      pharmacy april-june        0     5    NaN   NaN     NaN
                      sept-dec                 854  1211   60.0   0.0    60.0
               2026.0 AUG-OCT PHARMACY           0     6    NaN   NaN     NaN
                      JAN-APRIL 2026             1     1    0.0   0.0     0.0
                      jan-april                469   861   60.0   0.0    60.0
                      jan-april dual            48    89   60.0   0.0    52.3
                      may-aug                  433   669   60.0   0.0    60.0
                      may-aug dual              39    48   60.0   0.0    52.3

                                                   std          var  first  \
student_gender year   attachment_period
FEMALE         2023.0 August-November        11.746095   137.970759   60.0
                      May Attachment               NaN          NaN    NaN
                      Sept - Nov              9.180018    84.272727   60.0
               2024.0 AUG-DEC                 5.828527    33.971729   60.0
                      DUAL SEP - NOV         17.242132   297.291111   12.5
                      January -  April       11.611699   134.831553   60.0
                      MAY - JULY             10.275825   105.592578   60.0
                      Nov - Dec                    NaN          NaN    0.0
                      Sep - Dec               7.641627    58.394461   60.0
               2025.0 JAN-APRIL DUAL         31.718194  1006.043824   30.7
                      Jan-April               8.123321    65.988342   60.0
                      May - Aug              11.019629   121.432222   60.0
                      PHARMACY JULY-AUG            NaN          NaN    NaN
                      SEPT-DEC dual           9.242501    85.423833   41.9
                      may-aug dual training  11.176736   124.919433   26.1
                      pharmacy april-june          NaN          NaN    NaN
                      sept-dec               10.781480   116.240301   60.0
               2026.0 AUG-OCT PHARMACY             NaN          NaN    NaN
                      jan-april               9.043597    81.786642   29.3
                      jan-april dual         13.323896   177.526203   58.3
                      may-aug                23.389714   547.078716   60.0
                      may-aug dual           23.832672   567.996242    0.0
MALE           2023.0 August-November        14.523126   210.921196   41.1
                      May Attachment               NaN          NaN    NaN
                      Sept - Nov              7.015527    49.217619   60.0
               2024.0 AUG-DEC                 2.431049     5.910000   60.0
                      DUAL SEP - NOV         12.219536   149.317071   49.9
                      January -  April       10.529738   110.875381   60.0
                      MAY - JULY              9.249450    85.552329   60.0
                      Nov - Dec               0.000000     0.000000   60.0
                      Sep - Dec               7.950860    63.216174   60.0
               2025.0 JAN-APRIL DUAL         25.372922   643.785158   26.1
                      Jan-April               8.290999    68.740660   60.0
                      May - Aug              13.642582   186.120056   60.0
                      PHARMACY JULY-AUG            NaN          NaN    NaN
                      SEPT-DEC dual          21.284566   453.032767   49.1
                      may-aug dual training  11.880806   141.153556   45.8
                      pharmacy april-june          NaN          NaN    NaN
                      sept-dec               11.107835   123.384005   38.6
               2026.0 AUG-OCT PHARMACY             NaN          NaN    NaN
                      JAN-APRIL 2026               NaN          NaN    0.0
                      jan-april              11.520857   132.730155   60.0
                      jan-april dual         17.465264   305.035461   50.1
                      may-aug                26.959161   726.796343    0.0
                      may-aug dual           28.642607   820.398920   57.8

                                              last  nunique       mean
student_gender year   attachment_period
FEMALE         2023.0 August-November         60.0       23  53.978378
                      May Attachment           NaN        0        NaN
                      Sept - Nov              18.0        4  57.000000
               2024.0 AUG-DEC                 41.4       18  57.367742
                      DUAL SEP - NOV          55.3        9  35.188889
                      January -  April        60.0       45  54.280952
                      MAY - JULY              60.0       43  55.968936
                      Nov - Dec                0.0        1   0.000000
                      Sep - Dec               60.0       82  56.853159
               2025.0 JAN-APRIL DUAL         103.0       17  52.350000
                      Jan-April               60.0       77  56.759583
                      May - Aug               56.0      101  55.616920
                      PHARMACY JULY-AUG        NaN        0        NaN
                      SEPT-DEC dual           56.4       12  50.562500
                      may-aug dual training   45.7       24  44.412000
                      pharmacy april-june      NaN        0        NaN
                      sept-dec                60.0       71  56.660000
               2026.0 AUG-OCT PHARMACY         NaN        0        NaN
                      jan-april               60.0       75  56.264183
                      jan-april dual          58.3       26  49.847059
                      may-aug                 60.0       58  46.223565
                      may-aug dual             0.0        6  13.972222
MALE           2023.0 August-November         55.3       37  52.282609
                      May Attachment           NaN        0        NaN
                      Sept - Nov              60.0        4  56.919048
               2024.0 AUG-DEC                 60.0        5  59.000000
                      DUAL SEP - NOV          31.8       41  51.718182
                      January -  April        56.5       34  54.711644
                      MAY - JULY              60.0       26  56.761500
                      Nov - Dec               60.0        1  60.000000
                      Sep - Dec               60.0       72  57.024222
               2025.0 JAN-APRIL DUAL          45.0       17  55.310000
                      Jan-April               60.0       61  57.191379
                      May - Aug               60.0       97  53.996667
                      PHARMACY JULY-AUG        NaN        0        NaN
                      SEPT-DEC dual            0.0       19  38.912000
                      may-aug dual training   60.0       34  49.431111
                      pharmacy april-june      NaN        0        NaN
                      sept-dec                60.0       94  56.030679
               2026.0 AUG-OCT PHARMACY         NaN        0        NaN
                      JAN-APRIL 2026           0.0        1   0.000000
                      jan-april               60.0       76  55.456503
                      jan-april dual          45.9       38  46.433333
                      may-aug                 43.8       59  39.868129
                      may-aug dual            60.0       15  32.994872

In [56]:
##FINDING THE PLACEMENT RATE
df.groupby('student_gender')['placement_status'].value_counts(normalize=True)*100

student_gender  placement_status
FEMALE          Placed              83.941718
                Not Placed          16.058282
MALE            Placed              62.068966
                Not Placed          37.931034
Name: proportion, dtype: float64

In [60]:
df.groupby(['student_gender','year'])['placement_status'].value_counts(normalize=True).mul(100).round(2)

student_gender  year    placement_status
FEMALE          2023.0  Placed              79.72
                        Not Placed          20.28
                2024.0  Placed              85.95
                        Not Placed          14.05
                2025.0  Placed              88.91
                        Not Placed          11.09
                2026.0  Placed              80.83
                        Not Placed          19.17
MALE            2023.0  Placed              69.19
                        Not Placed          30.81
                2024.0  Placed              86.94
                        Not Placed          13.06
                2025.0  Placed              84.04
                        Not Placed          15.96
                2026.0  Placed              69.95
                        Not Placed          30.05
Name: proportion, dtype: float64

In [62]:
##COUNT NUMBER OF STUDENT PER COMPNANY
df['company_name'].value_counts()

company_name
NYERI WATER AND SANITATION COMPANY     238
GANTO ENTERPRISES LIMITED              227
COUNTY GOVERNMENT OF NYERI             153
PARKLANE CONSTRUCTION LIMITED          146
NYERI COUNTY REFERRAL HOSPITAL         144
                                      ...
ORANGI METAL WORK                        1
SMART FABRICATORS LIMITED                1
Jowaki engineers company                 1
JUJA FABRICATORS                         1
JOWAW COMPANY                            1
Name: count, Length: 4418, dtype: int64

In [67]:
df.groupby(['company_name','student_gender'])['student_final_score'].agg([
    'size','max','min','mean'
])

,,size,max,min,mean
company_name,student_gender,,,,
SMOOTH ENGINEERING CONSTRUCTION,FEMALE,1,93.0,93.0,93.0
THE REAL FASHION DESIGN NYAYUKI,FEMALE,1,NaN,NaN,NaN
237 YOUNG TOUR TRAVELS,MALE,1,100.0,100.0,100.0
2J ENGINEERING WORKS,MALE,1,NaN,NaN,NaN
2KEI GENERAL FABRICATORS,MALE,1,NaN,NaN,NaN
...,...,...,...,...,...
winnie salon and kinyozi,FEMALE,1,NaN,NaN,NaN
wonders electrical and cctv installation and services,MALE,1,97.0,97.0,97.0
yemken for industry and trade,FEMALE,1,95.0,95.0,95.0
young Kimoto construction company limited,MALE,2,NaN,NaN,NaN
ÑICE DIGITAL HOTEL,FEMALE,2,100.0,99.0,99.5

In [72]:
##FINDING COMPANIES WITH THE MOST STUDENTS
df.groupby(['company_name','year']).size().sort_values(ascending=False)

company_name                         year
GANTO ENTERPRISES LIMITED            2025.0    101
NYERI WATER AND SANITATION COMPANY   2025.0     99
PARKLANE CONSTRUCTION LIMITED        2025.0     91
SHYAM   GENERAL  MERCHANT            2025.0     83
GANTO ENTERPRISES LIMITED            2024.0     63
                                              ...
AAA GROWERS COMPANY LIMITED          2025.0      1
AAA  GROWERS  LIMITED                2025.0      1
A1 CRAFTTSE                          2024.0      1
A-ONE AUTO SERVICE LTD.              2024.0      1
47INVESTMENTS LIMITED                2024.0      1
Length: 6110, dtype: int64

In [74]:
list(df.columns)

['student_name',
 'student_class',
 'student_course',
 'student_year',
 'student_gender',
 'student_category',
 'student_adm_no',
 'attachment_period',
 'year',
 'attachment_start_date',
 'attachment_end_date',
 'company_name',
 'sector_name',
 'placement_status',
 'graded',
 'assigned_manual',
 'student_workbehaviour_grading_score',
 'student_skills_grading_score',
 'student_knowledge_grading_score',
 'student_final_score']

In [80]:
#FIN
df.groupby('student_gender').agg(
    avarage_final_score=('student_final_score','mean'),
    highest_skill_score=('student_workbehaviour_grading_score','mean'),
    total_student=('student_adm_no','nunique')
)

                avarage_final_score  highest_skill_score  total_student
student_gender
FEMALE                    93.489197            18.039662           4942
MALE                      92.929444            17.207163           8507